include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    invalid_annotation_target: ignore
  exclude:
    - build/**
    - android/**
    - web/**

linter:
  rules:
    avoid_print: true
    use_build_context_synchronously: true
