include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    invalid_annotation_target: ignore
    unnecessary_const: ignore
    prefer_const_constructors: ignore
    prefer_const_declarations: ignore
    prefer_const_constructors_in_immutables: ignore

linter:
  rules:
    avoid_print: true
    use_build_context_synchronously: true
